version: "3.4"
services:
  api:
    container_name: api
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    command: npm run dev
